#!/usr/bin/env node
/**
 * build-chrome.mjs — one source of truth for the site header, footer,
 * audience directory and the CSS that styles them.
 *
 * The site has no framework and no runtime includes: every page is standalone
 * hand-written HTML, and the chrome used to be physically duplicated in each
 * one. Six different navigations had drifted apart as a result. This script
 * rewrites the chrome in place from partials/, so changing a nav link means
 * editing exactly one file.
 *
 *   node tools/build-chrome.mjs           rewrite every page
 *   node tools/build-chrome.mjs --check   verify, change nothing, exit 1 on drift
 *
 * It is idempotent. Running it twice produces the same bytes.
 *
 * On the first run over a page it wraps the existing header / footer /
 * audience-directory blocks in marker comments; from then on it replaces what
 * is between the markers. Everything outside the markers is left alone.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

/* Pages the chrome must never touch:
   - course/     the gated member area, noindex, its own shell
   - .vercel/    build output
   - partials/   the sources themselves
   - the Google Search Console verification file, which must stay byte-exact */
const SKIP_DIRS = new Set(['.git', '.vercel', 'node_modules', 'partials', 'tools', 'course', 'course-content', 'assets', 'api']);
const SKIP_FILES = new Set(['google039507930feb61d1.html']);

const read = (p) => readFileSync(join(ROOT, p), 'utf8');

const HEADER = read('partials/site-head.html').trim();
const FOOTER = read('partials/site-footer.html').trim();
const AUDIENCE = read('partials/audience-directory.html').trim();
const CSS = read('partials/site-chrome.css').trimEnd();
const SUBNAV = JSON.parse(read('partials/subnav.json'));

/* The organisation, publisher and website nodes every other node references by
   @id. Emitted on every page so those references resolve wherever a visitor
   or a crawler enters the site, not only on the homepage. Re-serialised here
   so a syntax error in the partial fails the build rather than shipping. */
const SITE_SCHEMA = JSON.stringify(JSON.parse(read('partials/site-schema.json')), null, 2);

const AUDIENCE_DEFAULT = SUBNAV._audience_default;

const GENERATED = 'DO NOT EDIT BELOW — generated by tools/build-chrome.mjs from partials/';

/* ---------- helpers ---------- */

function walk(dir, out = []) {
  for (const entry of readdirSync(join(ROOT, dir || '.'))) {
    const rel = dir ? join(dir, entry) : entry;
    if (SKIP_DIRS.has(entry) || SKIP_FILES.has(entry)) continue;
    const st = statSync(join(ROOT, rel));
    if (st.isDirectory()) walk(rel, out);
    else if (entry.endsWith('.html')) out.push(rel.split(sep).join('/'));
  }
  return out;
}

const openTag = (name) => `<!-- @chrome:${name} — ${GENERATED} -->`;
const closeTag = (name) => `<!-- @endchrome:${name} -->`;

/** Replace the region between markers, or wrap `fallback` in markers on first run. */
function replaceRegion(html, name, content, fallbackPattern) {
  const marked = new RegExp(
    `${escapeRe(openTag(name))}[\\s\\S]*?${escapeRe(closeTag(name))}`
  );
  const block = `${openTag(name)}\n${content}\n${closeTag(name)}`;

  if (marked.test(html)) return html.replace(marked, block);

  const m = html.match(fallbackPattern);
  if (!m) return null; // caller decides whether that is fatal
  return html.replace(fallbackPattern, block);
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Which nav link, if any, represents this page. */
function currentNavHref(page) {
  if (page === 'index.html') return null; // the brand mark is the home link
  const dir = '/' + page.replace(/index\.html$/, '');
  const known = ['/who-its-for/', '/kids-and-teens/', '/book/', '/blog/', '/about/', '/contact/'];
  if (known.includes(dir)) return dir;
  if (page.startsWith('blog/')) return '/blog/';
  return null;
}

function markCurrent(headerHtml, page) {
  const href = currentNavHref(page);
  if (!href) return headerHtml;
  return headerHtml.replace(
    new RegExp(`(<a class="lnk"[^>]*href="${escapeRe(href)}")`),
    '$1 aria-current="page"'
  );
}

function subnavFor(page, html, warn) {
  let items = SUBNAV[page];
  if (!items && /^for-[a-z-]+\/index\.html$/.test(page)) items = AUDIENCE_DEFAULT;
  if (!items || !items.length) return '';

  // A sub-nav pointing at a section that no longer exists is worse than none.
  const live = items.filter((it) => {
    const id = it.href.slice(1);
    const present = new RegExp(`id=["']${escapeRe(id)}["']`).test(html);
    if (!present) warn(`${page}: sub-nav target ${it.href} has no matching id, dropped`);
    return present;
  });
  if (!live.length) return '';

  const links = live.map((it) => `    <a href="${it.href}">${it.label}</a>`).join('\n');
  return `<nav class="subnav" aria-label="On this page">\n  <div class="wrap">\n${links}\n  </div>\n</nav>`;
}

/* ---------- social cards (FT-05) ----------
   Twenty-five pages declared twitter:card=summary_large_image with no
   twitter:image, so the card could never render one, and /free-lesson/
   declared card=player with none of the twitter:player properties that card
   type requires, which makes it invalid rather than merely plain. An invalid
   player card is worse than a correct summary card, so it is downgraded.

   The Twitter set is derived from the page's own og: tags rather than
   authored twice, so the two can no longer disagree. */

const SITE_OG_IMAGE = 'https://www.clearedfortakeoff.com.au/assets/og-image.jpg';
const SITE_NAME = 'Cleared For Take-Off Academy';

function metaContent(html, attr, value) {
  const m = html.match(new RegExp(`<meta[^>]*${attr}=["']${escapeRe(value)}["'][^>]*>`, 'i'));
  if (!m) return null;
  const c = m[0].match(/content=["']([^"']*)["']/i);
  return c ? c[1] : null;
}

const decodeEnt = (s) => String(s).replace(/&amp;/g, '&');
const attrEscape = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

function socialBlock(html) {
  const title = metaContent(html, 'property', 'og:title')
    || (html.match(/<title>([^<]*)<\/title>/i)?.[1] ?? SITE_NAME);
  const desc = metaContent(html, 'property', 'og:description')
    || metaContent(html, 'name', 'description') || '';
  const image = metaContent(html, 'property', 'og:image') || SITE_OG_IMAGE;
  const alt = decodeEnt(title);

  const out = [
    `<meta property="og:image:alt" content="${attrEscape(alt)}" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${attrEscape(decodeEnt(title))}" />`,
  ];
  if (desc) out.push(`<meta name="twitter:description" content="${attrEscape(decodeEnt(desc))}" />`);
  out.push(`<meta name="twitter:image" content="${attrEscape(image)}" />`);
  out.push(`<meta name="twitter:image:alt" content="${attrEscape(alt)}" />`);
  return out.join('\n');
}

/** Strip page-authored twitter:* and og:image:alt so the generated block is the only copy. */
const stripSocial = (html) => html
  .replace(/^[ \t]*<meta[^>]*name=["']twitter:[^"']*["'][^>]*>[ \t]*\n?/gim, '')
  .replace(/^[ \t]*<meta[^>]*property=["']og:image:alt["'][^>]*>[ \t]*\n?/gim, '');

/* ---------- the pass ---------- */

const pages = walk('').sort();
const problems = [];
const drifted = [];
let written = 0;

for (const page of pages) {
  const original = read(page);
  let html = original;
  const warn = (m) => problems.push(m);

  /* 1. header — matches either legacy class */
  const withHeader = replaceRegion(
    html,
    'header',
    markCurrent(HEADER, page),
    /<header class="(?:site-head|head)"[\s\S]*?<\/header>/
  );
  if (withHeader === null) { warn(`${page}: no site header found, skipped entirely`); continue; }
  html = withHeader;

  /* 2. sub-nav, immediately after the header, never replacing it */
  const sub = subnavFor(page, html, warn);
  const subBlock = sub ? `\n${openTag('subnav')}\n${sub}\n${closeTag('subnav')}` : '';
  const existingSub = new RegExp(`\\n?${escapeRe(openTag('subnav'))}[\\s\\S]*?${escapeRe(closeTag('subnav'))}`);
  html = existingSub.test(html)
    ? html.replace(existingSub, subBlock)
    : html.replace(closeTag('header'), closeTag('header') + subBlock);

  /* 3. audience directory */
  if (/@chrome:audience|class="audindex"/.test(html)) {
    html = replaceRegion(html, 'audience', AUDIENCE, /<section class="audindex"[\s\S]*?<\/section>/) ?? html;
  }

  /* 4. footer */
  const withFooter = replaceRegion(html, 'footer', FOOTER, /<footer[\s\S]*?<\/footer>/);
  if (withFooter === null) warn(`${page}: no footer found`);
  else html = withFooter;

  /* 5. chrome CSS, last in <head> so it wins on source order against the
        older .head / .site-head rules still inlined in the page */
  const styleBlock = `${openTag('css')}\n<style id="site-chrome">\n${CSS}\n</style>\n${closeTag('css')}`;
  const existingCss = new RegExp(`${escapeRe(openTag('css'))}[\\s\\S]*?${escapeRe(closeTag('css'))}`);
  if (existingCss.test(html)) {
    html = html.replace(existingCss, styleBlock);
  } else if (html.includes('</head>')) {
    html = html.replace('</head>', `${styleBlock}\n</head>`);
  } else {
    warn(`${page}: no </head>, chrome CSS not injected`);
  }

  /* 5a. social cards, derived from the page's own og: tags.
        \n? on both sides of the marker so re-running never accumulates blank lines. */
  const socialMarked = new RegExp(`\\n?${escapeRe(openTag('social'))}[\\s\\S]*?${escapeRe(closeTag('social'))}\\n?`);
  html = html.replace(socialMarked, '\n');
  html = stripSocial(html);
  if (html.includes('</head>')) {
    html = html.replace('</head>', `${openTag('social')}\n${socialBlock(html)}\n${closeTag('social')}\n</head>`);
  }

  /* 5b. the shared entity graph, site-wide */
  const schemaBlock = `${openTag('schema')}\n<script type="application/ld+json" id="site-graph">\n${SITE_SCHEMA}\n</script>\n${closeTag('schema')}`;
  const existingSchema = new RegExp(`${escapeRe(openTag('schema'))}[\\s\\S]*?${escapeRe(closeTag('schema'))}`);
  if (existingSchema.test(html)) {
    html = html.replace(existingSchema, schemaBlock);
  } else if (html.includes('</head>')) {
    html = html.replace('</head>', `${schemaBlock}\n</head>`);
  }

  /* 6. chrome behaviour */
  if (!html.includes('/assets/site-chrome.js')) {
    html = html.replace('</body>', '<script src="/assets/site-chrome.js" defer></script>\n</body>');
  }

  if (html !== original) {
    drifted.push(page);
    if (!CHECK) { writeFileSync(join(ROOT, page), html); written++; }
  }
}

/* ---------- report ---------- */

for (const p of problems) console.warn('  warn  ' + p);

if (CHECK) {
  if (drifted.length) {
    console.error(`\n✗ ${drifted.length} page(s) out of sync with partials/:`);
    for (const p of drifted) console.error('    ' + p);
    console.error('\nRun: node tools/build-chrome.mjs');
    process.exit(1);
  }
  console.log(`✓ ${pages.length} pages in sync with partials/`);
} else {
  console.log(`\n✓ chrome written to ${written} of ${pages.length} pages`);
  if (problems.length) console.log(`  ${problems.length} warning(s) above`);
}
